export type HeroImageMapping = {
  [heroName: string]: string;
};

// Use `import.meta.env.BASE_URL` to ensure correct paths on GitHub Pages
export const heroImages: HeroImageMapping = {
  "D.Va": `${import.meta.env.BASE_URL}heroThumbs/dva.png`,
  Doomfist: `${import.meta.env.BASE_URL}heroThumbs/doomfist.png`,
  Hazard: `${import.meta.env.BASE_URL}heroThumbs/hazard.png`,
  Mauga: `${import.meta.env.BASE_URL}heroThumbs/mauga.png`,
  Ramattra: `${import.meta.env.BASE_URL}heroThumbs/ramattra.png`,
  Sigma: `${import.meta.env.BASE_URL}heroThumbs/sigma.png`,
  "Wrecking Ball": `${import.meta.env.BASE_URL}heroThumbs/wreckingball.png`,
  Reaper: `${import.meta.env.BASE_URL}heroThumbs/reaper.png`,
  Ashe: `${import.meta.env.BASE_URL}heroThumbs/ashe.png`,
  Bastion: `${import.meta.env.BASE_URL}heroThumbs/bastion.png`,
  Cassidy: `${import.meta.env.BASE_URL}heroThumbs/cassidy.png`,
  Echo: `${import.meta.env.BASE_URL}heroThumbs/echo.png`,
  Venture: `${import.meta.env.BASE_URL}heroThumbs/venture.png`,
  Tracer: `${import.meta.env.BASE_URL}heroThumbs/tracer.png`,
  Torbjörn: `${import.meta.env.BASE_URL}heroThumbs/torbjorn.png`,
  Sombra: `${import.meta.env.BASE_URL}heroThumbs/sombra.png`,
  "Soldier: 76": `${import.meta.env.BASE_URL}heroThumbs/soldier76.png`,
  Sojourn: `${import.meta.env.BASE_URL}heroThumbs/sojourn.png`,
  Pharah: `${import.meta.env.BASE_URL}heroThumbs/pharah.png`,
  Junkrat: `${import.meta.env.BASE_URL}heroThumbs/junkrat.png`,
  Genji: `${import.meta.env.BASE_URL}heroThumbs/genji.png`,
  Hanzo: `${import.meta.env.BASE_URL}heroThumbs/hanzo.png`,
  Ana: `${import.meta.env.BASE_URL}heroThumbs/ana.png`,
  Juno: `${import.meta.env.BASE_URL}heroThumbs/juno.png`,
  Zenyatta: `${import.meta.env.BASE_URL}heroThumbs/zenyatta.png`,
  Baptiste: `${import.meta.env.BASE_URL}heroThumbs/baptiste.png`,
  Brigitte: `${import.meta.env.BASE_URL}heroThumbs/brigitte.png`,
  Illari: `${import.meta.env.BASE_URL}heroThumbs/illari.png`,
  Kiriko: `${import.meta.env.BASE_URL}heroThumbs/kiriko.png`,
  Lifeweaver: `${import.meta.env.BASE_URL}heroThumbs/lifeweaver.png`,
  Lúcio: `${import.meta.env.BASE_URL}heroThumbs/lucio.png`,
  Mercy: `${import.meta.env.BASE_URL}heroThumbs/mercy.png`,
  Moira: `${import.meta.env.BASE_URL}heroThumbs/moira.png`,
  Mei: `${import.meta.env.BASE_URL}heroThumbs/mei.png`,
  Widowmaker: `${import.meta.env.BASE_URL}heroThumbs/widowmaker.png`,
};
